### ISSUE TITLE
Vulnerable to JavaScript interface injection

### ISSUE THREAD

**Issue by GouravdeepSingh** [payu-intrepos/Android-Custom-Browser#14]
Hi, i am using custom-browser version 7.2.2 in Android app. Today, i find following security alert on google play console: 

**Security alert**

**Your app includes a WebView that is vulnerable to JavaScript interface injection. Please see [this Google Help Center article ](https://support.google.com/faqs/answer/9095419)for details.**

**Vulnerable locations:**
**com.payu.custombrowser.c->L
Please fix the issue before: 02/13/2019**

According to alert, there is webview security issue in custom-browser.
please check this issue as soon as possible.

**Comment by pavanjaju** [comment]
I am also having this issue, I am also not sure whether they will remove the app or it just a deadline. Solve it asap.

**Comment by himgupta229** [comment]
Hi,
We have updated CustomBrowser to version 7.3.0 and [Option#2](https://support.google.com/faqs/answer/9095419) is now implemented.

**Comment by himgupta229** [comment]
Closing issue as there has been no update.
