### ISSUE TITLE
Custom Browser crash due to analytics library

### ISSUE THREAD

**Issue by sarthakgandhidunzo** [payu-intrepos/Android-Custom-Browser#27]
Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;)V in class Lcom/payu/payuanalytics/analytics/factory/AnalyticsFactory; or its super classes (declaration of 'com.payu.payuanalytics.analytics.factory.AnalyticsFactory' appears in /data/app/~~jDV-fdOswpX8xpJxmkovYw==/runner.dunzo.com.dunzo_runner.debug-YkSC1V9xFH09WubtKOyg0Q==/base.apk!classes20.dex)
       at com.payu.custombrowser.CustomBrowser.addCustomBrowser(SourceFile:1)
       
SDK version: 'in.payu:payu-custom-browser:7.10.6'

**Comment by shahfaizalc** [comment]
hi @sarthakgandhidunzo  this issue would come when older version of Analytics lib and new version both present in your external libraries. 

1. Can you please list what are other payu sdks used in  your app. Please update them to the latest.
2.  Check analyitcs version in  external libraries 
3. if you still face issue please let us know. our integration team will help you on this.

**Comment by sarthakgandhidunzo** [comment]
@shahfaizalc 
We are using the following SDK's

in.payu:payu-custom-browser:7.10.6
in.payu:upisdk:1.5.4
in.payu:payu-gpay:2.4.0
in.payu:payu-sdk:5.4.7

All of them are the latest SDK's. Correct me if need to upgrade any of these.

**Comment by shahfaizalc** [comment]
@sarthakgandhidunzo  please reach us via mobile.integration@payu.in
