### ISSUE TITLE
How to set PayUWebViewClient to setWebView Client??

### ISSUE THREAD

**Issue by sandeepsmane** [payu-intrepos/Android-Custom-Browser#6]
I am trying to do  

 mWebView.setWebViewClient(new PayUWebViewClient(bank));  
but it is giving me error. i think there is issue with magicRetryWebView. How can I fix that. Please help!!

**Comment by arshu-dev** [comment]
I got the fix both the issues: #6 #7 . Its all related to the latest update of Magic Retry.

First download the latest SDK & Magic Retry library from the below links:
https://github.com/payu-intrepos/Android-Custom-Browser/blob/master/CustomBrowser-release.aar
https://github.com/payu-intrepos/magicretry/blob/master/magicretry-release.aar

Then add it to your libs folder. Now you are all set to sail again. Happy Coding :+1:
